import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

export class MuSeReportGenerator {
	constructor() {
		this.logFilePath = path.join("/app/MuSe/sumo/results/sumo-log.txt");
		this.outputDir = path.join("/app/MuSe/sumo/results/");
		this.reportData = {};
	}

	// Parsea il file di log per estrarre i dati
	parseLogFile() {
		try {
			const logContent = fs.readFileSync(this.logFilePath, "utf8");

			// Estrai contract path
			const contractMatch = logContent.match(/Contracts to be mutated.*?:\s*\(1\):\s*-\s*(.+)/);
			const contractPath = contractMatch ? contractMatch[1].trim() : "";
			const contractName = path.basename(contractPath);

			// Estrai test file path
			const testMatch = logContent.match(/Tests to be run.*?:\s*\(1\):\s*-\s*(.+)/);
			const testPath = testMatch ? testMatch[1].trim() : "";
			const testFile = path.basename(testPath);

			// Estrai numero totale di mutanti
			const totalMutantsMatch = logContent.match(/(\d+) mutation\(s\) found in ([\d.]+) seconds/);
			const totalMutants = totalMutantsMatch ? parseInt(totalMutantsMatch[1]) : 0;
			const generationTime = totalMutantsMatch ? totalMutantsMatch[2] : "0";

			// Estrai mutanti testati
			const testedMutantsMatch = logContent.match(/- Tested mutants: (\d+)/);
			const testedMutants = testedMutantsMatch ? parseInt(testedMutantsMatch[1]) : 0;

			// Estrai mutanti vivi
			const liveMutantsMatch = logContent.match(/- Live mutants: (\d+)\s+--- Live: "([^"]+)"/);
			const liveMutantsCount = liveMutantsMatch ? parseInt(liveMutantsMatch[1]) : 0;
			const liveMutantsList = liveMutantsMatch ? liveMutantsMatch[2].split(", ").map((m) => m.trim()) : [];

			// Estrai mutanti uccisi
			const killedMutantsMatch = logContent.match(/- Killed mutants: (\d+)\s+--- Killed: "([^"]+)"/);
			const killedMutantsCount = killedMutantsMatch ? parseInt(killedMutantsMatch[1]) : 0;
			const killedMutantsList = killedMutantsMatch ? killedMutantsMatch[2].split(", ").map((m) => m.trim()) : [];

			// Estrai mutation score
			const scoreMatch = logContent.match(/MUTATION SCORE = ([\d.]+)/);
			const mutationScore = scoreMatch ? parseFloat(scoreMatch[1]) : 0;

			// Estrai durata
			const durationMatch = logContent.match(/(\d+) mutant\(s\) tested in ([\d.]+) minutes/);
			const duration = durationMatch ? durationMatch[2] : "0";

			const mutantDetailsPattern = /Mutant (\w+) was generated by (\w+)/g;
			const mutantDetails = {};
			let match;
			while ((match = mutantDetailsPattern.exec(logContent)) !== null) {
				mutantDetails[match[1]] = match[2]; // mutantId -> mutationType
			}

			this.reportData = {
				contractName,
				contractPath,
				testFile,
				testPath,
				totalMutants,
				testedMutants,
				liveMutantsCount,
				killedMutantsCount,
				mutationScore,
				duration,
				generationTime,
				liveMutantsList,
				killedMutantsList,
				mutantDetails,
			};

			return this.reportData;
		} catch (error) {
			console.error("Errore nel parsing del log file:", error);
			return null;
		}
	}

	// Genera il template HTML
	generateHTMLTemplate() {
		return `<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MuSe Testing Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 15px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        
        .header {
            background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        
        .logo {
            width: 280px; /* Aumentata la larghezza per un formato rettangolare */
            height: 120px;
            margin: 0 auto 20px;
            background: rgba(255,255,255,0.1);
            border-radius: 10px; /* Cambiato da 50% a 10px per angoli arrotondati rettangolari */
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 36px;
            font-weight: bold;
            overflow: hidden; /* Per contenere l'immagine */
        }

        .logo img {
            width: 100%;
            height: 100%;
            object-fit: contain; /* Cambiato da cover a contain per mantenere le proporzioni */
            border-radius: 10px; /* Stesso border-radius del contenitore */
        }
        .header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        }
        
        .subtitle {
            opacity: 0.9;
            font-size: 1.1em;
        }
        
        .summary {
            padding: 40px;
            background: #f8f9fc;
        }
        
        .info-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        
        .info-card {
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.07);
            border-left: 4px solid #667eea;
        }
        
        .info-card h3 {
            color: #2d3748;
            margin-bottom: 8px;
            font-size: 0.9em;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
         .info-card .value {
            font-size: 1.8em;
            font-weight: bold;
            color: #1a202c;
            overflow: hidden; /* Keeps the text within the container */
            word-wrap: break-word; /* Allows breaking long words */
            word-break: break-word; /* Ensures proper word breaking */
        }
        
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        
        .stat-card {
            background: white;
            padding: 25px;
            border-radius: 10px;
            text-align: center;
            box-shadow: 0 4px 6px rgba(0,0,0,0.07);
            cursor: pointer;
            transition: all 0.3s ease;
            position: relative;
            overflow: hidden;
        }
        
        .stat-card::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 4px;
            background: linear-gradient(90deg, #667eea, #764ba2);
        }
        
        .stat-card:hover {
            transform: translateY(-2px);
            box-shadow: 0 8px 20px rgba(0,0,0,0.15);
        }
        
        .stat-card.live::before {
            background: linear-gradient(90deg, #e53e3e, #fc8181);
        }
        
        .stat-card.killed::before {
            background: linear-gradient(90deg, #38a169, #68d391);
        }
        
        .stat-card.score::before {
            background: linear-gradient(90deg, #3182ce, #63b3ed);
        }
        
        .stat-number {
            font-size: 3em;
            font-weight: bold;
            margin-bottom: 10px;
        }
        
        .stat-card.live .stat-number {
            color: #e53e3e;
        }
        
        .stat-card.killed .stat-number {
            color: #38a169;
        }
        
        .stat-card.score .stat-number {
            color: #3182ce;
        }
        
        .stat-label {
            font-size: 0.9em;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            color: #718096;
            font-weight: 600;
        }
        
        .mutants-section {
            padding: 40px;
            background: white;
        }
        
        .section-title {
            font-size: 1.8em;
            color: #2d3748;
            margin-bottom: 25px;
            display: flex;
            align-items: center;
        }
        
        .section-title::before {
            content: '';
            width: 4px;
            height: 30px;
            background: linear-gradient(135deg, #667eea, #764ba2);
            margin-right: 15px;
            border-radius: 2px;
        }
        
        .mutants-container {
            display: none;
            margin-top: 20px;
        }
        
        .mutants-container.active {
            display: block;
            animation: fadeIn 0.3s ease;
        }
        
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
        }
        
        .mutants-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
            gap: 15px;
            margin-bottom: 20px;
        }
        
        .mutant-item {
            background: #f7fafc;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            transition: all 0.3s ease;
            border: 2px solid transparent;
            font-family: 'Courier New', monospace;
            font-size: 1.5em;
        }
        
        .mutant-item.live {
            border-left: 4px solid #e53e3e;
        }
        
        .mutant-item.killed {
            border-left: 4px solid #38a169;
        }
        
        .footer {
            background: #f8f9fc;
            padding: 20px;
            text-align: center;
            color: #718096;
            font-size: 0.9em;
        }
        
        .timestamp {
            position: absolute;
            top: 10px;
            right: 20px;
            font-size: 0.8em;
            opacity: 0.7;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="timestamp">Generated: {{TIMESTAMP}}</div>
            <div class="logo">
            <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAjwAAAENCAYAAAALwb8PAAAAAXNSR0IArs4c6QAAAU5lWElmTU0AKgAAAAgACAESAAMAAAABAAEAAAEaAAUAAAABAAAAbgEbAAUAAAABAAAAdgEoAAMAAAABAAIAAAExAAIAAACCAAAAfgEyAAIAAAAUAAABAAE7AAIAAAAQAAABFIdpAAQAAAABAAABJAAAAAAAAABgAAAAAQAAAGAAAAABQ2FudmEgKFJlbmRlcmVyKSBkb2M9REFHbHY1YVl4WWMgdXNlcj1VQUV5UUtWSnkwWSBicmFuZD1CQUV5UU8tbVVwcyB0ZW1wbGF0ZT1CbGFjayBNb2Rlcm4gV2UgQXJlIEhpcmluZyBKb2IgVmFjYW5jeSBMaW5rZWRJbiBQb3N0ADIwMjU6MDY6MTIgMTU6MTk6MDAAR2VyYXJkbyBJdWxpYW5vAAADoAEAAwAAAAEAAQAAoAIABAAAAAEAAAI8oAMABAAAAAEAAAENAAAAAGeet4sAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAqVaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOmV4aWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vZXhpZi8xLjAvIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgICAgICAgICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICAgICAgICAgICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIKICAgICAgICAgICAgeG1sbnM6QXR0cmliPSJodHRwOi8vbnMuYXR0cmlidXRpb24uY29tL2Fkcy8xLjAvIgogICAgICAgICAgICB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIKICAgICAgICAgICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyI+CiAgICAgICAgIDxleGlmOkNvbG9yU3BhY2U+MTwvZXhpZjpDb2xvclNwYWNlPgogICAgICAgICA8ZXhpZjpQaXhlbFhEaW1lbnNpb24+MTIwMDwvZXhpZjpQaXhlbFhEaW1lbnNpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWURpbWVuc2lvbj4xMjAwPC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgICAgPHRpZmY6SW1hZ2VMZW5ndGg+MTIwMDwvdGlmZjpJbWFnZUxlbmd0aD4KICAgICAgICAgPHRpZmY6UmVzb2x1dGlvblVuaXQ+MjwvdGlmZjpSZXNvbHV0aW9uVW5pdD4KICAgICAgICAgPHRpZmY6SW1hZ2VXaWR0aD4xMjAwPC90aWZmOkltYWdlV2lkdGg+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgICAgIDx0aWZmOlhSZXNvbHV0aW9uPjk2PC90aWZmOlhSZXNvbHV0aW9uPgogICAgICAgICA8dGlmZjpZUmVzb2x1dGlvbj45NjwvdGlmZjpZUmVzb2x1dGlvbj4KICAgICAgICAgPGRjOnRpdGxlPgogICAgICAgICAgICA8cmRmOkFsdD4KICAgICAgICAgICAgICAgPHJkZjpsaSB4bWw6bGFuZz0ieC1kZWZhdWx0Ij5NdVNlIC0gMTwvcmRmOmxpPgogICAgICAgICAgICA8L3JkZjpBbHQ+CiAgICAgICAgIDwvZGM6dGl0bGU+CiAgICAgICAgIDxkYzpjcmVhdG9yPgogICAgICAgICAgICA8cmRmOlNlcT4KICAgICAgICAgICAgICAgPHJkZjpsaT5HZXJhcmRvIEl1bGlhbm88L3JkZjpsaT4KICAgICAgICAgICAgPC9yZGY6U2VxPgogICAgICAgICA8L2RjOmNyZWF0b3I+CiAgICAgICAgIDx4bXA6TW9kaWZ5RGF0ZT4yMDI1LTA2LTEyVDE1OjE5KzAyOjAwPC94bXA6TW9kaWZ5RGF0ZT4KICAgICAgICAgPHhtcDpDcmVhdG9yVG9vbD5DYW52YSAoUmVuZGVyZXIpIGRvYz1EQUdsdjVhWXhZYyB1c2VyPVVBRXlRS1ZKeTBZIGJyYW5kPUJBRXlRTy1tVXBzIHRlbXBsYXRlPUJsYWNrIE1vZGVybiBXZSBBcmUgSGlyaW5nIEpvYiBWYWNhbmN5IExpbmtlZEluIFBvc3Q8L3htcDpDcmVhdG9yVG9vbD4KICAgICAgICAgPHhtcDpNZXRhZGF0YURhdGU+MjAyNS0wNi0xMlQxNToxOSswMjowMDwveG1wOk1ldGFkYXRhRGF0ZT4KICAgICAgICAgPHBob3Rvc2hvcDpJQ0NQcm9maWxlPnNSR0IgSUVDNjE5NjYtMi4xPC9waG90b3Nob3A6SUNDUHJvZmlsZT4KICAgICAgICAgPHBob3Rvc2hvcDpDb2xvck1vZGU+MzwvcGhvdG9zaG9wOkNvbG9yTW9kZT4KICAgICAgICAgPEF0dHJpYjpBZHM+CiAgICAgICAgICAgIDxyZGY6U2VxPgogICAgICAgICAgICAgICA8cmRmOmxpIHJkZjpwYXJzZVR5cGU9IlJlc291cmNlIj4KICAgICAgICAgICAgICAgICAgPEF0dHJpYjpUb3VjaFR5cGU+MjwvQXR0cmliOlRvdWNoVHlwZT4KICAgICAgICAgICAgICAgICAgPEF0dHJpYjpDcmVhdGVkPjIwMjUtMDYtMTI8L0F0dHJpYjpDcmVhdGVkPgogICAgICAgICAgICAgICAgICA8QXR0cmliOkV4dElkPmQ3Mjk0MDIzLTQ5MjctNDQ3NS1iODU5LTU5ZDRhOTVmZjIyYjwvQXR0cmliOkV4dElkPgogICAgICAgICAgICAgICAgICA8QXR0cmliOkZiSWQ+NTI1MjY1OTE0MTc5NTgwPC9BdHRyaWI6RmJJZD4KICAgICAgICAgICAgICAgPC9yZGY6bGk+CiAgICAgICAgICAgIDwvcmRmOlNlcT4KICAgICAgICAgPC9BdHRyaWI6QWRzPgogICAgICAgICA8eG1wTU06SGlzdG9yeT4KICAgICAgICAgICAgPHJkZjpTZXE+CiAgICAgICAgICAgICAgIDxyZGY6bGkgcmRmOnBhcnNlVHlwZT0iUmVzb3VyY2UiPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6c29mdHdhcmVBZ2VudD5BZmZpbml0eSBQaG90byAyIDIuNS4zPC9zdEV2dDpzb2Z0d2FyZUFnZW50PgogICAgICAgICAgICAgICAgICA8c3RFdnQ6YWN0aW9uPnByb2R1Y2VkPC9zdEV2dDphY3Rpb24+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDp3aGVuPjIwMjUtMDYtMTJUMTU6MTkrMDI6MDA8L3N0RXZ0OndoZW4+CiAgICAgICAgICAgICAgIDwvcmRmOmxpPgogICAgICAgICAgICA8L3JkZjpTZXE+CiAgICAgICAgIDwveG1wTU06SGlzdG9yeT4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+ClQzu9gAAEAASURBVHgB7Z0JnBXVne9PL/RCd9PQzSLQgKyyBGzMCGqAJKJkXBARozAjkIh7NChOXF4QEeEpvNEBNWoIvic4EzCCwij4SVRUYGLAcUAMEAU1CogsDTYN9H77nf+9Xd3V1bWcqluntvurzwdu1Vn+///5nlr+fVbGcIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACICARAJporJnzJgxQiTt+++//7d9+/adFElrlebCCy/sPnjw4O5W6T7//POT77333t+s0iHeGwILFy58+L777ptL2vi9sKd///6DvdEMLSAAAiAAAiCQBIEGm0cSqlpktaO2RUZc+EJg3rx5D5jVmS9GQSkIgAAIgAAIiBIw+4jpxT355JMTRWUbpdOTaxYm2gJlpA/hyRGgVh2z+lHiktOC3CAAAiAAAiAgkYDysbLzm6w5dnRR2lgsVp6sTuR3TkC0voYOHTrQuRbkBAEQAAEQAAGJBEQ/Zup0yZhDY3fUskTPk9GJvM4JvPPOO+tF64jSOdeEnCAAAiAAAiDgjIDQoGWnH6k0fjgxy2t9TmxEnmYCduvL6X3RrBFnIAACIAACIGCPQLq95EgNAiAAAiAAAiAAAuEjINXhKSoqamcXyfbt27fazROk9NTaIXIEyWbFFqtZVupyKXnwCwIgAAIgAAJhICDV4SkrK7M9kLi0tFRovZ8wwA2bjcOGDTvXic12uqhOnTrlyhpNTuxEHhAAARAAgdQlINXhSV2sKLkRgYKCgkKjOISDAAiAAAiAgCwC0h2etWvXrhQ1nrpMRNMiXbAIiLTyiKQJVqlgDQiAAAiAQFQIWDo8ya6bMmHChMlRgYVymBMgh+all176nV4qODt6VBAGAiAAAiAQGAIVFRXl6sGqTs5FCjNz5sybnchW5xHRIzuN2h6zc9l2OJFPrXFmNqvjnMhHHhAAARAAARDwi4BlC09+fr7tmVbawtCHUhumvV68ePFSbZjda1qw0G4epAcBEAABEAABEIg+AUuHJ0wI3n333TfCZC9sBQEQAAEQAAEQ8IZApjdqGJs0adLla9as2aCnT6QFSC+fNiw7O7tUG4ZrEAABEACBBAG33rXgCQJBI0DjR6dNm3aLmV2etfCsXr16vZkhiDMnMHr06BH0sjI6nCzyaK7R/9g777xzoFF5lfD58+d7sm6Tok/7W1VV9ar/pGABCIAACKQ2galTp95sRcByryt6wVsJEY3Xm6lDs8B27ty5R1SGW+n0bNGT7Wb59eRrw7R2OdGvyHCSV2uP29eKbUZyX3zxxWnTp09fbhRvFr5ly5bp3DFcYZSG8zjC4zoZxSvhsVhsR0ZGxvB+/fq127t3r/DimR9++OEtI0aM0J2lpsjGLwj4SSCI7wQ/eUB3tAhYfV88a+EhrHoPmx/OThiqWJm15sRW4nzJJZeMcpLXrzzr16+fRXY7dXbI7lGjRi0nGdu2bTPy9C2dHZKTnp5eSnLsODuU7/zzz19K+egcBwiAAAiAQLAIeNrCQ0XXemB+fSC0dhhVi9f2kV20FIAbs+OMyuRnuB53WYy1umTp0eP5xhtvXDN+/PjX9OIQBgJ+EfDyGfCrjNCbugS073wtCU9beEi5eqyJ6EahY8aMGak1PKrXu3bt2h5VZ0evzmS+gGXK1iuLOuzKK6/E2B41EJyDAAiAgM8EXGvhIc9K9AOjeGF20oumFeWp2GCV3m29VvqiHq/m7hVbRadX+tR1qOhWh+EcBPwi4Mcz4FdZoTf1CFi9b01beEpKSrCQX+rdM56U2MsXr5e6tPBo4LM2DNcgAAIgAALeEzB1eP74xz/aWshv9+7dO0SKsGLFCuHBncXFxdhdWwRqiNJwByTmtbn19fXbvdZJ+uwOfPbDRugEARAAgVQgYNqlZecvY6UpyU4eEcCy5VrZ4HZ5rPRFPZ7qM2xMlXuQ6obbTs6a6XOjrUN1fm0crkHASwJhe/a8ZANd4Sdg9a41beEJf/G9KwGBpkNUYyJ14v9hw4YNEs2npHv00UcfVMtQzpV4O79K3nXr1q0SzafkUX5F8/E1bmgtHFtH//79CxU9yi+fAVViS4iDxKSD9Kmz8sv0BQsWpMwgenXZcQ4CIAACYSbQ4mWuLYidvwaUD8Ozzz77xO233z5LK8vJtSKT8tqxRUSXWrZZelG9ijy76Z2UTdFlZLeoDUp+RR7tlj5hwoTJSrjZr5JHSWNXp5LP6lerR5telt677rpr0DPPPPM3rT7l2o5eqzIoMvELArIJ2LlvZdsC+SDgNgGrd63rDg8VwK2HSm28WzIVwGrZSpjer6heRZ7d9KRTNA+lVfTQudnhRGbQHB4ZZTVjpo4T0S3KWESWWjfOQUAWAdF7VpZ+yAUBmQSs3rXo0pJJ30fZVhXvo2miqqtEEyIdCIAACIAACFgRcMXhofEkakVTpky5Rn3t5DwCH2wnxTbNk0p/nfH6zzWFoYrEvaKCgVMQAAEQAAFdAq44PHPmzHlcLX3VqlVYUl8NxKXzcePGjXFJFMSAAAiAAAiAQEoRcMXhcZuYXkvGnj17Un4X6ln8cJs15IGAxwSyiooYFmP0GDrUgQAI8I2hZUFwMtVasYXvVt3KrsGDB9+ixLvxO2nSpMvdkOOljMsuu2yil/r81PXKK69ME9V/8uTJpaJpkc4/AgUFrOMt83s9P+cPQ8t79We2l2Lwz3JoBgEQiAKBVo6FW4X65JNPDKf0uqUjGTmrV69eb5X/kksuGWWVJqjxeq1kQbVVz65rr712uV64XlhBQcHNeuEICxaBnsPaDx02usPPD395iPUtZWO5dVnBshDWgAAIRJmAocPzzjvvWDoEMsBs3Lhxgwy5TmS+9dZbm53kk5lHxJEZPXr0CCc2HOOHk3yy8lRUVFjuOM55eL5NhazyRlxu/sWTiu8sP1bNYrUVbPB5bAIvb0bEy4zigQAIBIiAocNz8cUXJ93l42T2zNixY6/wis+uXbsM91eS3boj4rgYcTDLO2/evAc2bdq01SivWfiSJUt+YxavjisqKmoah2FmjzqP3fP8/PyJXLbhysyNek3XkrKrE+mlEMga+9NO1/cdmndNrL6WZfP5dyV92SWsiLWRog1CQQAEQECHQKZOWMoE8XFBpfTR1DpmjR9SYQ779u3bI5xYldCuHlVWW4sVqvOZndvphiwrKys3k2UUR6xtlruTzfRGqhHuD4HcH15TfO3EO7svO3m8luW1S2OnqhvilnRMZ3m8SfGkP2ZBKwiAQKoRCJTDo13Px6vKSPaDyvd6GuyVrdADAmEhQIOUL5/R/e4x13T69ZmKeu7sZHBHna8W3tiunFXAZ2sdY4fCUh7YCQIgEG4Cht0BdpwAbQuJFomoLLfkaPXLvlbbvWLFiqVTp04N1SBatf2ideWUqaJLth6tfaTXjk7FTq0c9bWoPBFZarlROO82IGvgzQ/3Xdmxe1ZpTWWMZWansQw+Yqeu5hQ7fWw/P69l//4EG/fXreytKJQXZQABEBAjIPreFJPWMpXVu9ZwDE9LMbgyIqBtlZo2bZqr0+eN9IY9fPfu3c94VYannnpqtFe6oIflXnRZ0bW/XjZ4T+ce2aX1tQ0sKzedOzhp1A3L/9Xz/eASXVpFnVlPzitQrcyoPxAAgegSCEwLD5+GfMWaNWtMZ2jJ9AydVrGeRxlEO83Kpy2DTPvVumKx2BF+3cnMtmTjvv7667m9evV6hOTYKZfaTiMbROWJyDLSEabwjh3bdr36l53mDf9Rh5uo66oh1hDvvuLljxcjFqtjtZUnWFX5IZaeHmNb3mQPvfH/2CIeWROmcsJWEAAB5wRE35tONFi9a5Nu4REZsGtlBBXMytmxW3gRnXZlatMb6TAK1+bXu04mr568IIfx9SU782UIWuzD5qa9CxYsGKk4O27KhaxWBDIHlLY9f/aqfnuH/7DDTUosjdXh97NySR4Qo1la/CQe1jafFTdH4gwEQAAE5BJI2uG5hh9yTXQuXabzYCV79uzZ9zqxnLxfK9kicouLiwtF0umlcUO/nly9ML4MweMy9JFMXgfb9HQizFUCWWMmdLxu5lMDtrXJSs9jjf4N+Tm8CpoVUXdWfR2L1VU1dWll52CLiWZAOAMBEJBNIGmHR3QqM5/GfNSoMD169CgxitOEV2muLS/pw5fMx1+r4O67776FZGrDtde8deHJSy+91PbYkXXr1q0iWaRjzJgxI7VyRa4p7/Hjx5Oa7ksyRHS5lYb0XXTRRaL3gaFakkOHYQJEuEkg/6pbut19/b0l/2EllHdfsvrayrjDo6StqWanlXP8ggAIgIBsAoYOT+KzYf2/qIEdO3bsbCTtwIEDB0Xk8Py5RjK04Wp59PFX4rWDjNXpjM537NixTcnPF+cT3sT07bff3kL5Fi1aNNdIthJOzg2lvfrqq6coYZs3b27Sq4QZ/ZJDSfnpUNIkrqz/V9Jrf5Wc2nCd6yolrdWvTt6moA8++OCgkn/Dhg3CLWRbtmyZruRrEqZzoqQR+dXJ3ipIRA6laZUxGgGFE3/R7Vc/uaHzQqvi8EZL3pVVzWdoVfBerTruzCdynD6BKelW7BAPAiDgHoGovozdIwRJIAACWgJtx1zdadb1s7o/qo3Qu66vq2G1VSdY7ZkyxmLN45Nf/R27bttb7BW9PAgDARCIJoFQD1qOZpWgVCAAAgYEsrr2zpkk6uzE+Lider72Tl1VOR/DQwOWm49DXzBHK5Q3S8AZCIAACIgTMOzSEheBlCAAAqlCoG1bdu59SwesECkvTUOnbqzayuMtBisreb87wr5Vzq1+O3ZkXcdOLpox9cHC+6zSIh4EQAAE9Ahg0S89KggDARDQI9DxriUDHsvKtv47iVp26qpPxp2d+tozfPJWy03tv/6UbaioEB60nHvOD4rGXHN7z2Wnjn3OuPPz0jFsSaFXPwgDARAwIWD95jLJjCgQAIHUIXDh5R3G9Tyn7VjzEtMA5RrehfVdfMyOnrND+d9/nT3BfyrNZSViO3RgWedeVDi+4rsatv+zSnbuD5mj2YsiupAGBEAgugTg8ES3blGyVCNQwnIHDM3pQ90/bhedZF45o9sjJJdWUdY7GvjCgvW1VXFHp+bMMVZf17plh/JVnWZHDnzKtuvJ0AvLK8ruNHhk4T9XVlSx+vp0NvRCNkEvHcJAAARAwIwAHB4zOogDgRAR+MdRmSN/8WTPP19339nUepLrpukDLij6QftObfqRTGVauVp+Q6yed2GdYjWnj8a7sRr4NHS+e5Y6SdP56ufZDeXlrKIpwPwk65zz2/+wvr6Btc1PY+mZ6eysnuxn5lkQCwIgAAKtCcDhac0EISAQSgIDR9aNr6+r6zLkgvZTup2TTRtzunLwLqXCEZcW3aAnjNbYoWnnNWdOsJpTRxKzsWLN20do82z9E1vAd0jfwsPrtHF610Xdcrv8ZGrnBbQdRWZWjOXmJVqYCnuyDnrpEQYCIAACRgTg8BiRQTgIhIxA57PYxPJvv+UOSAO7+KrOtKdVlhtFKO7Rtm//4fmtupGoVYemnNecPswdniO8O4sWTq43VLl3J3v57ZfZYp5AaOwOT5d72dTiKXkFGV3S09PiG5Fm5yRajfr1Y70NFSECBEAABHQIwOHRgYIgEAgbgaIi1i49g/WurMpg5cfOsAuuLP6XPgPzznGjHD0G5pUqcqhFJ7FyMi0m+B2r5s4ODVCmBQXT0vS7sCjv9i3s6T8sYXfymVnHFFkWv1mDzs/7wUVXdIyv5EyyaaZXm6yEjnPOZcMt8iMaBEAABFoQgMPTAgcuQCCcBLoNYN3J8uycNNa2HWPfHa1h9zzXb2dBAeuYVIk6sfwB5xX8mGTQOBo6aBZWDV9bh8br1Nec5g6QcasOpX9tGZvy8r+z2TacHdZ7QN6gX/xr/7coPw2S5m4WnbGMzPgF6zmAjaI4HCAAAiAgSgAOjygppAOBABMo6c96k2OQ2Yb/y2hgeYUZ7ExFPXv8jdKjXXrm9HFqetf8nOL+5+ZdlsjfOOW88gSr4/+Ugcm0Pw3p1h4fvsv+zxOzWH8+budVdpwJb2bbd2jb7//L7/rviA+ObpRLOsjhSedvrBgPKyxi/6jVh2sQAAEQMCOAhQfN6CAOBEJCoGdvNohMTc+Ixbuc2vDFAdN5N1BNdYw99NLAz1945KvLt2888abd4hS0y+qS2zajOMa9DOpSii8myLuwYnygMjkgdPDZ6ImZWwmvhH24kc364I9swzdfsq95tOh4nbis4aMKL5mxoPdbccmNXhTtv0r6ado76eRDh1hGBjuLX9AYpebNueIS8B8IgAAI6BOAw6PPBaEgECoCRV3Z98jg9DTuDfAuJvI9Mtrwgb7kKPB/N83tteF/flT4f1+Y8/c7eZSwE9KuKKNjXBj3QGhdnVq+ejLtfE4OSC13NXL45Pe0DMYOfsEWb9/EVn2xg33+zTfx1hy7jkjmJZM7/nziHSVL434O/ccdnXgrD3dyuJsT96zS0mJxh4fK2q0ba8d1iY4Joiw4QAAEUpgAHJ4UrnwUPToE2uax3okGF2rhqY+7CGlp6bwlRGkdaWDn/aj9jee9X3rjvKl/63v466ovREqf3zGzM6WrKKtkWVkVfIDymXgLEp80xY4fZu+/vYo9tH8v28PH51CXlV0nJ24CTXufPqfv8v7fL5igODtppEB9cP+nIRZr0ZJU1JN1ipLDM378+IH/+Z//uUddbKPzw4cPv3bWWWddYxSPcBAAgdYE4PC0ZoIQEAgdgcws1jPeDcSnhTfwfayo+4ccHjpoSndidlWi62nOvw/8/JWnD9703itHX7AoaFaHDm3OKjtUzWWeYfXVp/n4IC4/xqqen8d+8NWe+G7nwq1Ferr4TLKhs37bfyfFkY106Dk71GrV0JAoV7xni6fr3IOvKP2XcO64zsuaKGy8xPb/69Kly0QjGTz8ZHp6eqF9qcgBAtEmkHgjRruMKB0IpAKBDjSglxwDmkVFTo/6oHEwie6hROhP7+q+7L7fDnifX+Wr02nP27bP6Fh1up61Sf+WNdRVssNfsy2LbmfduLPzPzxtMs5O1k+mnvWLe5f235loy2l0dtRGtjCGx/PBOxTd6MexTt1YSYskAb548skn4w4KOSl0yDSV13W7hJbm/2fOnIlZbTKhQ3YoCLRq4ZH5MPIHUdNOHQpG0ozcvn371tLS0hHSFAgIjnKdyLyXBdDyj7N39zv3bzLS48sM0qDeKu7w8N6lNjmmZvYa1HbMbzaVVjw0+dOex7+p3K+TOCOnbXqHtjl/561EdSyLi3v5yfi2ECd00goHde7Muvzy2SFbOnRObFVBI3TMUJF3QIsckiNHh/ISKerEesYDAvyf3/eggmbx4sWb+T/l0tN7s0kpTkDAZwJo4fGxAvx2dnwsOlS7TKC2OjHtm5yBWF01X/W4kg8sbtnKo1WZGC/D2KOrzvn6vB8VXaCNp13K0zMa2mXlJF4T5cfYy4cOsa+06WxcZ543tsOVD68u/Zb25SL93CEwdXZINnXPxbjDQ04PHYob2bYgPlMrHhak/yZPntzUmhMku9S2kCOmHOpwnINAlAnA4Yly7QqUjV7OAslCl4Re5n4bzbsRbvbKhooT8SngcWeggTs6ddUVfPHjyqZxMXp2kOOgQJoxr+cHg37Q7nJ1uhO8HSenzeE2sbqqePB3x9lf1fF2zmkBxDse6/3ijDm9Xk/UTEKzWctOk3zu8FCLFY3hIZv5itLxgw/Udn1X+CadDk5KSkq60323cuXKVx1k9y0L2awcvhkBxSDgAQE4PB5ADrKKsL2cg8xSaxvvQliqDZN1ffgg+zgum5p4+BHjU8jrqr9LdG0lgnT/jzs9jV7PHQt6r+8zNO8SVcL02pqaRveCsVMn2RFVnOhpVq/BbYc/vr706JAfFP5zQlWiVUdpqTEXRNPq63h3Fh84zccn0aE4PG2yWLF5Xu9iyWHYv3//Ae80ytGkOD4vvvjiNDkaIBUE/CMAh8c/9tAsicDLL7/coqVCkppAif16L/uADCInIuHExPiaOeWstpIvEqgZwKw1XHE8aDbXvb/p/1bHbm3Oi6cpYBl8jR2+dnPiqD7FKpRzwd+8H/2009RfPTfgf6gpiX9MeTbrLiy1bMoSH79Ty1uZEt5SvHyUhg9edmVzVLU+u+dbt27dRE6C3XxBTz99+vTlVK5YLFYedFthHwiIEmg1aFk0I9JFhwC92LwcYCub3HXXXbdeto6gyf9iF9uq2ESf37jTwx2d2sqy+EWb3A68ZaTJd1GS6v7O+Y/B2375449pJeMWR02t+Do71IV13b1nLzzv4vY3kpCETY3NTy2kml/Ed2Tns8NoXFLQDnpugmaT2/bw90J8xheXW8XP+TKTOEAgvATQwhPeuoPlINBEgG/j8CVf+TjeAqO4FeT00Mym2spjfGfzE/y8lqc3/kYrn2++WGHG+Ju6PlTAU/PdKZoy8HHQicE8TVr1T3Las173/nbQxuE/Tjg7lEppRdLPYRDKDWqI1TZuUJoYv6NOWVfLkpotppZl51wZlGwnTwTS5pCDR9PrI1AWFCFFCcDhSdGK1xa7qKiI77Ed/iMV/uo2qKWad9ew++JxisfDL+JOD9/3qub0MVZzpozP3qLBv4n9trRy4q1Cje7N2Mmdftl9QPZ53N3hezokjrp6vqqh+ZFZ0idr6L+uK/28U0n20IS8Jn/JPKdObIyP2amv5Qse8n96B1/0+Vu9cJlhvIsnlsrj3u65555XU/gZk3lrQbYHBODweAA5DCrKysrQVx+GijKx8cO32Wq96LjjQS09Z7jTc/pIfMq6mdNDMjIz09kVPytcyDKbx8lw18XM4cnsM6Tt8AdfHLyT62sa6Cw0C0vH6Lh9vBuLNiulGVpUBu1xppx5OkiYPvRR6vrV8rRzTSzQ2mOHGNIGgQAcniDUAmxwhUC/fv0i0UplA0YujZXh6fMoD9/P6tgbK9h0vfxxh4FP66aurepThxPT1vnsJ/7d0ksedzAKO2aXduqS2JSUEvHeJeoT0zsy+UDnYbN+M2CbEmkgVom2+OVdWXz8UR0fJV3P/xkdX33m3bYS9IE3siNVw9Hak6o1H95yw+EJb925bvmGDRtCtX6IFsDevXtTqpXqhxPzRv10Vo9HRl/VbjxnEXd6trzBVn31N/a6lo1yzbcS5WNiKljNqW95i08ZHwxclVjUT/s95y0qbXIyWG5+Q9Pg5Vo+nEaRo/7Ny8saNHv5oI/iWz5wt4B8A70WGXUes3Pea8Tqak/HnTOaim4k6+Ot7DMzOW7FwdlxiyTkgIC/BODw+MR/7dq1K31Sbaj2sssuw4BEQzrBixg9od193x9bfMeE23o91759vKWHjKz5/RNseuWp5vEtrX0ZakGp4g7P0XhrD7Wi0KrM2kaMNlktZ30f1dl8IieH9brn2T5r2mQnXiU0xtlpNxYZn5iCfoYPtD4ed8YozOioLU8stmgU70Y4nB1ziujiM+eD2GARgMPjU31MmDBhsk+qI6n25MmTni3yFxCAeQX5Jy8hJyU3P6N973PbDeZ2xT2U8nJ24smZbOjJE+xzsrVet12GR9CgYL5WT/Vp3tpTyWdx8TEzfOEVyhI/Mtq0XLWitq7VtPQOl93YfX7X3jn94xl4605yzg5vfeItTjVnjvNWqERXllHrDun75ht2LK5X0n9wdizBCs3as5SCBCDgEQE4PB6BDouasL7kCwoKPNvGwU5dTpo0ScoiiN16s5KG2Gl2hns3dFz+865z+XiepjFMNJ7nf9/Khp44yv5vZku/RWM+b5Ph69zUnT7KHY2j3OFQb0ehM1K4OXfWxdd1vv7in3a8oSnINHlTKt0TcrSoe4262cgJ481Nhl1ZJODoIfYbXUEuBYb1OXCp+EJiuHOLdXmESCFRUAjA4QlKTcCOSBJYvXq1lEUQu/ZigwhY9SneLVVZx7qenTtixD92msCD1P1QlQt/wWb8+yL24xZw4+NsWoRw/6KW1VV9F5++Xldzml/H+ErGNNlK34vhM7LOnXRnt+fSM/TjW0o3vyJnh1p2aBYZ2RDXrSOWuuaU7rkP/8R+by7VeayXe6A5t9LfnPX19Z7OkPO3tNAeFQJweKJSky6WI2wbiqbiX+M9+7F/oCUByeFIT+POSm2MTbyz+7J/uLjDWH4rqJ0e9tf/Zu89cB3LXv8S+3n8NuHOBHUV0Y4T1IOlOBHxLi4+oLmOr85cX3MmsWeVqk+Jd43F+7toZtikX5Y85sYtl3B2+Jgd3rpUa+LsKLoUcz7978a9w5QIF3+93APNRbM9FZWZmdnDU4VQBgIuEIDD4wLEqIlI5YXVwlKXJf3YhdT4kpaeHndM0tITXUA/n9trw0VXFl3Fy9HC6eHXNZtfZy+S40MtPuXH2GcZvKuLZ487P+T4xJ0f2mmdj5+preLdSnzDzmZviF/yhhiSO3pSu8vOHtSWHKukjlisPj4bixZFNGvZUZQozs7/vMeeOHyYnVbC3fxNRefZLr/q6uoddvMgPQgEgQAcniDUAmxwTCAVNwrlsLLO6skuImhpfGkc6gLKyEzjg5N5kw8//ulXPV+5+vbutOpyfjyg5X811OLz2B3snMduZkUbXmI38RaeenJ86F8t93Hqaurig4Zp81Hu8bTI3bUr6zrun0qWtAi0fcGXb6Z1dqpO8unxR/h6O+W8DOZjdtQq3v1P9rz62q3zX//617PckhVlOTk5OcOjXD6ULboE+N+ILQ+Zf+FgCmMza5mcm7UkdxaG+kpJjkWs3ePPM/JGuMeTzXI7lLCMNopvk9Y02PfrT89seur+z27gM7x1JpS3vDe4I9Prxz9lvxo2iv2ims+9qa9PZ3mFOXxAc/O2DksfYSP6DEq/4Oo7v/cUtSw5Ocixof29yNmp44sgKttGKK03VjL37mQvvzCfSZnhGIZ7yYqP7PiKiorN7dq1GyNbD+RHl4DM58zqm+XsrRXdukDJQCDwBLrkN625w21Na5xKnlj/Ru049BzQdsyiNed+/b2RheOsCnXoEPvq90+xu5+6nw387gj7ICM9xqer17TI1qET637Z9E6LHDs7NDiZ70BKM7FozE6s0ZlS29xCoc4FX0n6f+kEJx20YsWKVFvWwBEzODuOsCFTQAjA4QlIRQTRjKBvKCrzL4Ug1odiU04ea6+c0y8t1qfpeWoaekODmm//P73/OOVXPf6VJ22atq7Orzqv47uuf7rsEXbVl3vYS+kZfFSz6jh3dN7onMKuOaogwVPeqhMfG8RXeOZ7edXyQdGxWMKZsuPsvP86u//w1+wLQaW2kk2dOjWQyxrYKoTkxMePH98gWQXEg4BUAnB4pOINt3BsKBrM+svLTWwjQdY18P2xYnyTKxrHoz7ijgTvsFZmYI0aX3zvv/1p6P4+Q/OGqtPpndMaPn96mS3g6/c0Cc3Iymfnje1zm156szCyq54PDKrliwmSsxPfDJS2izDLpBNX8R378s2X5Ky9g7E7OsB1goqLi6/QCUYQCISGABweH6rq2WeffcIHtZFSmYIbhTbVX1YuK2i64A5FQz13eHgLSqtmHh5Cjg+NmyHHJysno929v+m/8/KfdZ3Ko0yXI+QtPQe++TK9aXBwVn4XWpenbZNegZN4qw7ftqImvqjhMb756Bnu6PD1fQTyapMsnceoW07KzKz58+fjedQC11wfPHhwlSYIlyAQOgJweHyosttvvz00s0GCuqFoqm0Uqr5NM9qop5zzFYr59HFq5dF2ayl5+EA+5TT+e8WNXVb88/09FvOL+IajLSKbL2oP7Y99RpfpGdl8ULS4r0MOVn0tLSSYaNWhHdob4l1YLWd8NasyP6Np9EcPsH3mqRArk0BJSckUmfIhGwS8IACHxwvKIdaBDUWTr7zRo0ePSF5KswTuvyQGwPAgarlp4Htgxfhg4BjvKjI6ND4Pu/Dy4l/MXjHw3bw81sUgT82Jb9kJWpunTW4RbymiVZetj0SrDo3V4QsJ8pWTY3zXc6etOqRt1RJ2BU2jt9bsLEWqjgOzQ2v37t3P2EmPtCAQVAJweIJaM7DLkMB3330Xqhk1vJXsLcPCOIhIz2IV8Wzc2aG2G2rdqeeORXzzT/KArA7KxzN2PTvn/Hlrhu7Jac966WUp44v7nanqxjJzi/WiW4TFW3W440WbkMbH6tCqyUm06pDw15axcTv+i6XUQNmLLrqohKbW2jluuummkS0qw+WLIUOG3OWySIgDAV8IwOHxBXu4lAbtr+DCwsJQzajJz8+3mh1l64aoqmAn4hm40xJ3b+JdSGf4YoF8D6z4WB4LcZSv0S/Kzs3o8Ngrwz5rr+P01NS2re1ydifepWU63IfrpIHJtD3EsaZWHb6Sj4URxtHctqO/X8yGbv0Tc9VRNNbof4zi4HzwwQcH7VrzwgsvbFPy06+bs6k+/vjjJ+3ag/QgEFQCcHiCWjOwCwQMCJSfYGXqKGqtaYivXFze6PQ0Ta5SJ2txHs9DLT08NCs7PWv2yu/9t7Z7Ky09k6/ATCmaD2rJUR/x7SH4VhQ15Ozw1p0G2o7CaDCROqPB+ZGDbPHT97DBO//M/mqQxLXgoUOHDnRNmENBiqPiMLtuNppNpcitqanZo5tIMLC0tPRewaRIBgKBJwCHJ/BVFAwDg7KhaNBam/yona/2xB2eeLeWMjYnLY2vdVPHF/VrXL1YO01dz86408OdE/JhcvMyO962qP9/8HS5TWnT0prGClEYOTv8Q9oUTeN16vlmo7SuTn31SR7fct2epoQCJ2cq2EE+Xmfck/ewe775hh0TyJJ0kp07dyblDCRrADklycqwyp+dnT1YcX6s0mrjN27c+KA2DNcgEGYCcHjCXHse2o4NRT2Eba2q5sRR9golU38y42ve8GngcQeED2LWtsboiY1/c7kjQ04PX6Nn7JUzujb9Rc/X4Wk6tLKoZYe60Gr5vhW02WiDg7V1FOF/Wslun/crNpiP10mpLiyl/F79Ko7PmTNntonoHDt27OMi6ZAGBMJCAA5PWGoKdrJHH330cmBIEPj4L2yNlkW8xYY7HrS4Xw3fvoHG1WgdFW0euk7j3VZKusumd3m0R5+251N4XT1f4EfniDs7XHYd78Iip4f3Y9leW6e6kpWRo7NgBuu08TW+GehxdlJHVSSDevToUeJnwfLy8kaS82PWgsMH2jc5vn7aCt0g4CaBVk2q/MXXspPeRW30kLkoLrSiZDKWDcXPOgS35trt1o11/OVidrQ5pPmMnmCaRp6RXcCy8jryNXTyWnRFNafUP6urafhi5iUff+97o/JH3rag37uJVDQuiB5fZY2dsvgu53xOvK6QhA2to77czdb993vsxY92so1+Ozl+3U9+PkOtayTeVdnqnR80G/XsRlg4Cch87qzuW1WjdTjhwWoQSEUCNM7lwOdsQUlf9mtt+ZWWHhpXU8NbX9rwaeWZOTRRjHZSt/6bIzMrrc+E27tN/PyTk9+QbP6CiuejrLG62ngLUj3vxtJzdpQ/l9Rqjh1i23f+F3txz0ds4/7PGS1m2GJsEOlIlYO3UgZuXIzykVA+RMuXL5+eKvWBcqYWgVZvP+Wml4FBebBkyA6LzJkzZ968ePHiUK0jo2bLZ4AU8mmvnnc/yLwv1eWTdS7j3u/ej5Xc9b/ZfjObuavCMjJzWGbbYtYmp5A7Lom/cawcH9oC68UFf7/mZ7PPXheLNbB06vzmgfHustPH4t1lNFBaObQtOuXH2GcfbWLPf/oxe58Psv6Up5OyLYSi38mvH/eUjPvASdmRBwT8IiDzubN6vuDweFzrMivbq6JY3VQy7Ag7N1nMJt3G7jz/Yva0GfOGBt6yk5EVd3gyc4pYemZWY4tNq8e/hZgP3zn+/Plji26rq2tgGem8K6uebxfBnZ266nLu+7RcZ0dp0dnyJnvo04/YW3sPsD1+d1m1KIzOhR/3lKz7QKd4CAKBQBKQ+dxZPV+t3nh+GhPI2nHZKJl8XTbVUJzVTWWY0WEEbRQa9r2zaAVdJ4vKWSLrwvJ+eS9b3+1s9kOztPEWmHQ+riczj7f2FLFMPr4nLS0xZ4HXp1lWVldLLTx8MHRVeXy9HZr+TkvtUPsOtfzQlPL1L7E7v/or23rsWHzKfCi6rPx4Fr1+dkwrFpEg4AMBmc+d1fPV6k3npzE+sPdcpUy+XhVm3bp1q66++uopXumLArPq6uodOTk5w2Uw69iRdb33N+wr7re0sZbPH3lq7cluz8f2dIi3/JDDQ/+MjprKGHeUquPOTh3fMqK2pj7u6GTw7bXeWMGmf/w+21BR4c3aOUY22g0vKipqV1ZWVm43X7LprV7IycpHfhAIOgGZ73Or56vVW85PY4JeUW7YJ5OvG/aJyrC6sUTliKQDM2tKvQexXrc+wv5unbIxBc3i4rO3aJ+szOx809aeMxV1rE3WGVZz6iirPHWKjwpqYDVV7Ovlj7MrwjwI2Y/7ysvnRvheQEIQ8JCAzOfO6vnCOjweVjRU2SfAu7JCO8Dbfmmd5/hyD/vquYdZt+pqtkVICp+9Rask15w6FN//qqFxyR3+MmqdnQ9WbuCzs2orK1l2dgM7eYJ9/PyD7ALu7ND2D6HovmpdKH9CZL7s/SkRtIJAeAighcfjuorSC8/Km3YDLXjZo9iFj+kZ+09s8rAL2TKxnPwVwGduZfIt09vwsT3pGdmJ7i3u99CChDVVMb4bew0frMz3tKyP72bBlsxkZx86xL4Skx/cVH7dW148N8GlDstSnYDM587q2YLD4/HdJ7OyPS4KfRhb3T9u2wBejohmdu7Niq+/lT3bvQ+7RkgC7+LKzC7kTg9fqJBPY+eVy7PRCsx8KjpfTbny+N/jA5dfeZZN/Og9tlZIZsAT+XlvefHsBBw/zEtRAjKfO6vnCl1aKXrTuVFs2RuKynww3Ch/gGXUHfmSHX76AXY9bd3w6Q72e0tbG7ekoL2xYvVKLxUtOMgbdvg+EDRLi47PPhLsMrNUmNoJcG+ndv2j9P4QaPUXuswH0cr78geBt1pl8vW2JAltMusUrFyt0ayR49g1E29iK7VSWywamNaGZdEihblFfAYXn/TFI0/znUobag+xA/vS/vTM/2oYz/MrHpFWVKiug3B/yXx+QlUZMDZlCMh87qyeJ7TwpMxtFq6CYqNQ1+urZuuf2KoHrmNpj93MirZuZE07YbfomGzgg5P51PM6vus6dWfRUV+fWJ358MEGDFJ2uVro5c+nx5uulu2ySogDgZQlAIfHw6qfNGlS5Hb7luWtz549e72HVZNSqsrL2YnXnmcPkvPzzIOsP59i/r4aQEN9Nd86ooLvm1WVGMPDHZ4Y933Ky9gBdbqwn0+ZMkVsfJPkgvI1gUroOaIFNiWrgngQSGkC6NLysPplOQceFkFXlVUzom4mi8AospLByQKjcHRRd1Yy9W62smsvNorPQOc7reey7PyOLDOrHSv79hTLzfyKvf7/2A3/9Sb7D2GhIUgYxPssyPdJCKoUJgacgMxnzurZQQtPwG+OMJhHq9a6aSd/IBJ9KW4KDYCsIP8Ff/wgO7DkV2zczi3s1kw+dCctVsnX6anke2bVsob6xNo8vFICtwFoAKrVdRPog0CH64IjKnDFihVLE8SS/3/ZsmWm+9JFFGHKFAsOT8pUtbyCSliiv1XLozzrvZO8devWVgOGvdMupKny90+xF2m7CEpdX0W7ojc7PG3bsyohKSFKxMeKPRhUc+nzXVdXh/E9mgratWvXdrVrM3Xq1Js1SRxfzpgx4061bDp3LAwZA0cADk/gqiS1DQpyK0iyNcNbwlqM4dK+WGVeb968WfTFXfPJZvb6Zx+nv0Tlra6si28SWnUmjeXw3SicMpBZNj3ZonbOmTOnafC2aB4v02VkZMTH96S647N27dqVSj0PHjy41Ms6UPTSr9ut2V6WA7r4ZseAAAJuEKAXkhtywr4ruhsMZMi44IILhMXSoOb9n8VW09+2Z8rr42vx0PnRw6ytsBAkdJWA4vjQR9dVwQEXRuWlY8KECZODYCq1ZpM9vLV2UxDsgQ32CCTmm9rLg9Qg0IpA4wvJsx3UWxmAACECXTrkf2/8sG6r8nOyhsT4tzPGP58ZNC+9sRMxvU2sal/ml9OPlld+VV2Vxmprq/kWE7msLV98+VQ5+1arpCg3t8fwPh1+3qs4f1JBTtYwkqPuj6ypbzhWXtBrrjZfkK5poCN9xIJkk5ktiq1WAzTNZAQ9TiljUO0cMWLEaMXGKNdDUPk7tQsOj1NyyOc6AWwU6jrSJoHkhNx28aCGnDbNvVLp3NHh22W1OBpq03P61vZ9uW9+Ndvx3kHWfXAO61ZymGVkNLDc/MSg5Z5dcvpcNazP55np1g3EWRlpHbvWHX6mhRJcuEJA+eDefffdo5csWbLFFaE+C1HK5LMZttSTzbt3794xZMiQ4bYyIrHnBKzfWJ6bBIVhJZDsy4qP33Ft8GFYGcqym/8VytTOjqWe09ms9+E+rB3LYdVV2bTgMqs4nNn2l+OGNFxT2k/I2VF05BUUKqeB/Q3zX+mLFy/eTM/eyZMnQ9vNQrOjkn1/+Hlz0bgish9jfPysBWvdcHisGYU6xbp161aFugCSjA/zB04SklZi+fZarGpjLqv8vJh9ui2LjT2792ZqFYrq8W//9m+BnbElwrygoCDezRI2x4HspdlRImUMehpljE/Q7UxV++DwRLzmr776ak/H1TjdUDRsL+nw3TbOhqjQiki1Hxawdp/0Z9l12Y6KXVtdxU59d9xRXi8zzZo1K9AztuywoOeJDjt5vE47dOjQgUG30SmTqJbLKY+g5IPD41FNjB49eoRHqnxVs3Llyld9NQDKdQkk++1LpmXnzKmT7MiBv+vaFbTAqLX80YeXjqBxrqioKN+5c+eeoNnlpj3EHV1cbhJNXhYcnuQZCkl466233hdKKCERH9R4iwSxron0eqPQqH3UXKsIiYIaaDOukBzjx48vCYmpwmbSx5eOIKxzRXbk5+e7ujq7MAiPE1IX18KFCx/2WC3UGRBo1SFPN6NB2qSDU/lDI5OrWcUozL3Wr+g1s02J88s2r/VSedVcvNRfzzfI+pcrz1OQe/57+2O/YwOGi68FlKyBas5OZJ05c2Zlbm5uINZ+cWK/VZ5k+VjJN4r38p43ssGP8EWLFs29//77H/FDd9B0yrwHrO5rtPAE7W6APVIJVFdX75CqwEI4pt5bAApIdNu2bT0d++Z1semj884777iyWKio7TI/dKI2+JXuvvvumztz5kzMQvWrAhr1wuHxuQK8Uj9mzJiRXukiPaJ91/wl6GlfR05Ojq9rZWDqvZd3YXK6rP5aTE66/7kvvvjiyV45IV7p8Z+qsQV8+YClTid1GEtFjB0CcHjs0ApZWvXYHb6X0jYvzbexoWirblUv7YQuEDAjEHWnh8pOzggdZhySiZMpOxm7/MiLSR1+UG/WCYenmUXkzvjqq78LcqG8HkDJV0PFir9BviECalsqOD2EXoZjIkNmQG8TYbPARBiV6wnh8LiONLgCi4uLPV3y1mpDUa83CuVLv9+lrh3+4jmpvsY5CBgRIKensrIy8ot40seY1scx4mAnfNeuXdvtpE+ltHB6/KltODz+cPdF6/Hjxz39wAdlh2Mj2Pfcc88VRnEIBwEtARrIvGDBAk/Hwmlt8OKa1sepqqqqTEYXOU203UIyMqKet6SkpHvUyxi08sHhCVqNpIg9/K+/p70s6vLly6dr9UVlw0VtuXAtj8Ds2bO3pUIXV3Z2dk4yrRBBWlTwueeee5LqjI5hw4YN2rFjh6fjGY3uxv379x8wikO4HAJweORwDaxUeui9NM7opcn/+vN075yf/exnK7wsN3RFm0DjcyRtoG9Q6Bk9v2b2OcljJs9uHNWN+rjjjjvuVWR88sknfxs+fPhIdTxf+NS3PdSsuv0Vu/HrDgE4PO5wNJWCpktTPIgEgVAS4B9NvuOGt39A+AHKjgNz6623TvPDRtKpODF29c+ZM+dxystb75ocI7synKYPere/03IFNR8cHg9q5t13333LAzWBVcFfgperjbPzAlXnc3p+1VVXDXKaF/lAwIoAfSz5gpavWaULc7zoM/v8888v97qc1E1FdZCsXj4+K971lawcu/nRymOXmPP0rW4S0RvbiUo3bkonev3OI5OpWdnMeHttk9oWP3VreXltC+lXWHipG1tLaGtezrWXdSqnBOZSlXtXL5UfZTezR89G0TCvyyKrHKLl9TKdTLZWHNHC42VNQxfjy6uPSnUMfEn/B1KdQVTLTy9cOqJaPpkfK7vMZC6z4XUdjh49eoTd8iO9fQJweOwzQw4HBJQXJV9efbOD7I6z9O/f39O1h0QM5Uv6PyaSDmnCSyDu9UTU8VGeZXXt6IWp490+P3Xq1EnZy2xQV5nbdhvJ27Rp01ajOIS7RwAOj3ssQyXJ679g/IKzb98+T9ce8quc0BtMAlF1fLZv3+7rB7qgoED6HzI0oyuYdxWsckoADo9TcgHPF5S1JtSYvP4rUK0b5yDgJ4GoOT6lpaUjlA2CY/zwki3fImaHV/q8/MNw0qRJLSZ3eFXGVNIDhyeitT1+/PhrrIq2bds2T7uXrOxxO97Ll5XbtkNeNAlEyfFRNgj2+jnjW8QMj+LdsXr16vVRLFeQygSHJ0i14aItBw4cOGglbuTIkWOs0iAeBEDAfQKK41NfXx+IVX+dlrCioqLcaV7kAwGvCcDh8Zo49AWKAB/jE+gd5QMFC8a4TiAzMzO+6u8XX3zh22q/yRQqPz+/XTL5w5DX6xasMDAJq41weMJacy7ZvWjRorkuiQqUGNGXFJ/FdUugDIcxKUmgb9++8dV+//CHP2BDW4s7gMYCen1YmORaNF+242bXhEFQKwJweFohcTdAGdjnrlT3pN1///2PuCcNkkAABJIhcP31128gZz0VdmVPhlNU8/JlO5ZGtWxBKBccHsm18Oabb74hWQXEawjwv/4wFV3DBJfhIqDsyv7WW29ZTj4IV8lgLQj4RwAOj2T2I0aMGC1ZRdLir7322kg1o6enp0tfoyNp6BAAAgIExo0b91pj96xnU7EFzEISEAglATg8oaw2d41es2bNBnclQpoVAT93lbayDfHBI8CdnuGNjk/wjINFIBASAnB4QlJRMFOMwMGDB1eJpfQ3lR+7SvtbYmh3gwA5PUeOHLnXDVmQAQKpRgAOT6rVuEF5e/ToUWIQFargkpKSKaEyGMaCgE0CXbp0eRKtPTahITkIcAJweHAbxAmILFQIVCAAAsEhAKcnOHXhpiULFy582E15kNVMAA5PMwuchZzAhg0b0NQf8jqE+fYIwOmxxysMqadNm3ZTGOwMo41weMJYaxY28ymtjj78YX95XnHFFU9aoEE0CESOQNif28hVSJIFOuussyIxvCBJDFKyw+GRgtVfoXzRMnz4/a2CAGpP89emNJ/1+1t66drh9EhHDAURIACHJwKViCIwdvfddyez3lFD1BmmZ/j7qGdkZEYdMcoHAiAQcAL+vgUDDicVzQvrX4pLlizZ4rS+5s+ff6XTvGHJl5aWztIzMnwz10/dIoXm4ya6i6QLchq+wvjmINsH20DAbwJweCTWwNq1a1dKFA/RLhF46KGHUmLhxdy8ApeI2RfTJivbfiaPcpSXlz+8fPnyA7QhpUcqpajhK4yPkSIYQkEgIgTg8EisyAkTJkyWKB6iGwnwHc+xlYTA3ZBX2EEglZwkOXn5cgS7ILVdu3ZzFTFhd3qUcuAXBECgNQE4PK2ZpHxI2Lq19u3bh81CBe7avHbtBVLJSZLTNpgOj56DQ2FfffUV1kKRcytAKgj4RgAjCX1DD8Ug4C2B9h27eKuwUVsm785qWxCuRriePXvO5X7P3LA5/75UsIdKUR8ewo6gKrTwRLBS3SgSbzXZ44Yc2TLwAhQn3L7TWeKJXUzZkS8rwseXuCjRHVF6rTtayZTmzjvvHKgND+J1VVXV0iDaBZtAICgEgvcWCgqZFLeDj4sZnOIIIlf84rP8mYjUqeTswLE8fPjwLFGjnn766T0izpGoPFnpsrOzb5YlG3JBIAoE4PBEoRZRBhAQINClRx+BVO4n6da7v/tCk5TYuXPnJ+yKIKeHDrv5kB4EQCAYBODwBKMeAmnFCy+88EwgDWs0Ct1Z9mrnrLP9cTy6+qTXiE6yTgvl591HrxrJ9yM82TL5YTN0goDXBODweE1csj43x97cdNNNd0k2F+I9JJDPp6WX9BvkocaEqrMHl3quU7ZC3n00kZwM3jVmu6VItm1Rls8dzcoolw9lk0sADo9cvp5Lv4YfniuFwtAQGPgPozy1lRyswuLOnuo0U+Z2SwjvGpvlt+PjdpnM+Pkdxx3NHL9tgP7wEoDDE96607X8k08++ZtuhMPA2267bbrDrFKzoTvLGd6hF13sLKPDXN//8RUOc7qfbfPmzdPcl5qQqDg+3Pkol6VDK5e2w0glZ0cpf0lJiT+j7xUDGn937dq1PRX5azCE6hIOj6TqWrhwYSQWLvvtb3+7QhKiQIl98803XwuUQZKM6dF/COsxYIgk6S3FZmS2YaVjftIy0MerUaNGLfdAfTv6CNIhUxfJp+0wZOoIquz9+/f7Xm5ydgYPTvTVUl3QEVResKuZAByeZhaunt13331zXRUIYU0EKioqXN8k8YYbbvhZk4IIn/CWMXbxT2/0pIQX/OMk5tfaP9oC+vFBin8FG//T2uPk+sorr4y36PhRFif2ysyzffv2rTLlm8lWOzvqdEp9q8NwHiwCcHiCVR+BtGbYsGHej3Q1IcH3PnJ9k8Tjx4+nzPYU5466hA0YfoEJ4eSjaBuLn/zzrckLciDhL3/5S+Ba65SPofIrUiza3kJJT7+vv/667y0bInZ7kaa0tHTEpEmTLvdCl1oH1YPSsqMOV59TGjrUYTgPBoE0rRkyKyqVxl3I5KitM/W1LMZ+lUddNuU8FcqolFXW7/HD37CnZk1l5WVHpKi46ZFn2JCRP5Qi20qo9v4I0r1rZTvi7RG4++67b1myZMnv7OVyltrpfaS9H51pj04upxxFCFixRguPCEWkCQyBP//5z3MDY0yIDSnq0o3dPO8Z12dQpWdksCn3zvfN2dFWyaOPPup5K4DWBlzLI7B48eKlMj+giuXJ6KC8dCiy8OsfAbTwSGLv1w1u5eE6LW5RUVG7srIyz2agGNkpq3ykz686MyqrF+EnjnzDXnn6Ubbnwy1Jq+vUvRe7/u65rO/Qf0haVjIC1PdIKtZpMuzCnPfaa6+9Ys2aNRvcLIOM+0d9f7ppa1hkyWCqlN2KLRwehZTLvzIr1cxUqwo3y2sV51eZ1HZFvXzqsnp13tAQizs877/2Evts+19sq+3Ssw8bfdUUdv4lE1hWTq7t/G5nUO6RINyvbpctiPIuvfTS0R07duy0cuXKQKw+PXv27HsXLFjwZDKsaIFD2Wv+KPdpMnaGMa/M59KKKRweSXeMzEo1M9mqws3yWsX5VSbFrvnz51/x0EMPufoXnCKbfv0un9oWv86pxefzTz5i+z/bxY4c+Dsr+/YAqzxdwWr4AreZbbJYdm4eK+rSlXXs1jO+avPZg0pZ974DGb/v/DK5hV76+L799tvx5irUZws00i6Ud04QeT/33HNP3nHHHfdaFX706NEjNm3a5MvML4WflY1RiZd5n1ixbPWW8tOYqFQolUMmRzNOVhVullckzq9ykW1RLpsIe6SxJqDcI37ep9ZWRiuFwpxmTa1evXp9tErnXWkUjt5p9EeTzGfTiiEGLftT59AKAk0Eampq9jRd4CRpAny9mhEQrtbBAAASU0lEQVRJC4EAIQLqD4zb42eEDIhQIpmOQIQwJVUUODxJ4QtW5kWLFs0NlkXuWXPRRReVuCctWJL4WIHBwbIonNZQ9wVZzter8aVrIpzUnFv9wgsvPKPNrXaAtHG4BgG/CaBLS0INzJw582aaLilBtKlIr142fvwl4kXZ/CgXVSiVzS/dpjdUyCKJI1+Fuzw/P79dyEwPpbnEW8/wFStWLJ06derNenEIMyZgxNM4RzhjZL7rrBiihUfCPeOHsyOhGBDpIYEot2B5iJHB2fGG9pgxY0YaaeKbmt5iFIdwfQJRbp3XL7E/oXB4/OEeaq2nTp3ydBsGK6/dLZh8M8bpbsmyI+fCCy/s/sEHHxy0kwdpWxKge2TevHkPtAzFlSwCfOf5bWayvXpmzWwIU9z999//SJjsDautrZok/WxuCitErd0yGWp1qa+9fMl4Wcaolkupu+rq6h05OTnDZ8yYMWLZsmUYf6KAsfGr3CMxfijnNrIjqQ0Cdvh6+Z6wUYRAJbXDM1CGOzRG5j1hxRItPA4rDdlAwC0CfNByKcnig0BN/2p2S1/U5Khfcun8oIXnolbGoJRHzVrEJrOuL5H8UU9jl2fUecguHxwe2YQjKn/dunWrvChaqr0QUq28yd5DejOFaJVdcEyWbOv8PXr0sD1Tkrq+aMuH1tIQ4oQnqCVHAF1ayfHTzS2zyU5XYWOg1y95L8oZxTLp1aG6nHv37l3ar18/zHLRA6UJU3PTRMUvvbhH9fRGLYxaaqzG7ZiV2a+Zq2Y2+RknY98vP8tjR7fMZ9LqfQCHx05NCaaVWaFmJlhVtlleJ3FelDOKZdJjrS2nF2z17AhTmJaZme3gaUbHPE69XYd5SvNYGlTOt4Z5zDxV9GOnTJlyzapVq16Lfkn1SyjzWbR6J6BLS79OECpAQPZYCaubV8DE0CZJ5bKLVJpdPpTer1l4IuUJapri4uJCZW+yZG2cM2fO48OGDRuUrJww56eWslR2dvyuO7TwSKgBmR6smbl2PwJmskTjZJY1auUxY2pUVpl8zewJcpwRK1Gb+ay43VlZWSn94RVhlSxnMx2peF/L5GnGOmhxMuveijFaeIJ2N8CeOAHsL5W4Eawe4FS7XdzgQVt5uCEnyuxl85EtP2h1k2rlDRp/xR44PAoJl35px2CXRNkSU1ZWdtRWBpcSU/++S6JaiMH+Us048LJMsHCbA8mjo5k0zhJEvGFCunbv3r0jytS//fbbA1TOKJcxTGWDw+Nyba1evXq9yyKFxE2cOPFKoYQuJ3Krf99lsyInjl6a119/fUpO7+VN4CdlfjRINh2Ru2lsFOjRRx990A8GQ4YMGe6HXhtoHCelcnXt2rWHYwHI6DoBODyuI/VHYDJTRv2x2Fgr/6uv1S7MxqmjEcOnoVtuePmHP/xhQ1Q/Dka1SOXlawkWGsW7GU666HBTZtBlffTRR69RmWlAsZ+2kg07duyIxMKbNJmDyuMnT+gWJEADimQdgiaEOpksdlZy/YRWVFTUzso+O/F+luXkyZOb7NjqVlreJWm7ZdAt3UGUQ9ts+HkfkO5du3Y9HUQ2btjEu1pe9ZuvkX43yueHjO3bt2NbGKNKVYXLrBuVGt3TVl4oGaOb0oXAVPB6ZfIzqwK/2bpZbj/LQi0tfOG/cjPWsuKclttN9rLKJirXKQNR+U7TRYVx//79C/ft2+fp5r9RZ07dgX63kDll7Ec+mc+S1fsDXVp+1HgEdW7cuHGDG8WaP3++r+NUwvIxULOmh5wOWtBMHR6W8zNnzmxLlCC43QCKffQbFq6KnfzZjI/PIdvDdH+TvXTI/EAqjJz8JqzzvzvQie3I00iAbi5ZByCDAAh4Q6CkpKS7rOfYDbnvvPPOA96QkKuFWgTd4OG2jPHjxw+UW3J/pLvNya48f0odLa12mdtJb5uUHeF209o2BhlAAARcI3Do0KH9dp9Zt9LTOC/XChJwQXzfqFFucROUEws4EinmTZ48eaIgH8fJpBie4kIdV4ZARttoBWQ6TmLbGGQAARDwjMCyZcscDdLdunXrplRyaJKtED4b6Qm7L1E+TsSX9b2SLasf+RcuXPiwKF8aaDx06NBItob5wV5Ep2jdOElnpb9VfzQpscrkNJ76PJ3mRT4QAAEQAAEQAIFwE/DTx8Cg5XDfO7AeBEAABEAABEBAgAAcHgFISAICIAACIAACIBBuAnB4wl1/sB4EQAAEQAAEQECAABweAUhIAgIgAAIgAAIgEG4CcHjCXX+wHgRAAARAAARAQIBApkAaJAEBEAABEAABEJBAQHTWEmY5Jw8fLTzJM4QEEAABEAg9ATurc9Oif6EvcMgLoF5viO//tzvkxfHHfPI2ZR3+lAhaQQAEQAAEjAisXbt2ZTLvfMpvJBvh1gRE2SuS5s2b94BZHiVdUH/NbE82znaZk1Volt+2McgAAiAAAiAgjYDZ+9pJnDRDIyxYlDMhULfqmOWLMC53i2YGMdk4dy2FNBAAARAAAScE+Oat65N9nxvlX7FixVInNqVqHiOO2nDiow0zusZ2GYJ3kxFAN8IFTUAyEAABEAABSQQqKirK3Xifm8mQZHokxZpxVMfZdVIjCcvtQqkBu33utq2QBwIgAAIgIE7AavyHW+98cYuQ0i3mWjkg25pAq808CVrrZO6EYFqdOxwhBQRAAAScEJD5flfswXteISH2K6tOUA+t+WNaemsmCAEBEACByBGQ9WGNHCgUKLIE4PBEtmpRMBAAARDwlgBaFeTxtsP21KlTJ+VZEl7JcHjCW3ewHARAAASECNx6663ThBIiUSQIFBQUFEaiILILQc2esg7ZtkM+CIAACIBAawJ23+mtJTSHzJw582Y9ec0pcGaHgB5LvTBFpl6cOkxJh18BAmpwbp8LqEcSEAABEAABlwnYeZfbUa2Waycf0jYTUDM0O2/OwRitdaSXVp0G5wIE9CC6FSagHklAAARAAARcJiD6Dj927NgRu6ppDy67eZC+mYBo3TTnwJlTApiW7pQc8oEACIBASAjQR1XUVDuDY0VlIp0xAdG6Qb0YMxSNwaBlUVJIBwIgAAIgAAIgEFoCcHhCW3UwHARAAATcJ0AtDtgB3X2ukBhAAnSzyzoCWFyYBAIgAAKRJyC6y7b23S97E0qtPu21mxWjla29dkPX6NGjR2jlqq+LioraafWo483OtflkXdOYLCM73Fje4NChQ/uN5G/YsOFVWeXSlWtkiBvhugoRCAIgAAIgIJ1AMu/wSy65ZJRbBjq1w4l+r3Q50aOURzQvpZeVlmTb3WdNz3kjOXoH3T+itivpFGdbubb61dNrGWYlNJl4S+VIAAIgAAIgIIVAMu9uJS/t2O3UOLu7fSs6tb8i+r3SZbQmkdZmo2s7jgCV20iONlxWWq0euraqD708MsKs7KB4zNISoYQ0IAACIBABAiIfKNFi2pk15KZess9Mt1e6KioqyvPz81t1UYnys5uOyixaNjtp7dqhl96oPkTt1ZNpN8zIBrUcDFpW08A5CIAACESYgMhHQbT49DF79tlnn7BKL+OjZyTTKNzKRrN4PZm7du3a7qWzY2ZfEOL0GOmF+W0rWnj8rgHoBwEQAAEPCdDA2k2bNm11U6WRIyX7o6fW65UuGrtSVlZW7iY/EVlUVtEy2kkrols0jVIfonaKyhVJp+g2SwuHx4wO4kAABEAgogTc/ihpPzhuyzeqBi8/7l7q0pbXjm47abV6krkmvdu3b99aWlo6Ihk5TvKSbqt86NKyIoR4EAABEIggAZEPhJ1ik4OjzNyxs93E7t27d5At6uO2226bLqrbS1179+7dLWpXKqajQdh+ODuOWdNNK+twbBQyggAIgAAISCPg5jufjBSVZzXdXVSOSDovdYnYYzeNHa520qrt0K6Do44L+jmV2fYhs1C2jUEGEAABEAABzwjIfP/rybYqmF4ep2Fe6lJspLVt9PQq8XZ+SY5oejtpFZl6dlJYjB9KGhm/enppMLxdXXpytGGt+rxIiTYRrkEgKgS+++67tzt06HBpVMqDcoCADAL4DiRPlbrozKTYZUzyRPPYSUs2Uno3bTWTpcSdOnXqZEFBQaFyrfcrWl7Ka1UGSoMxPEQBR8oQyM3NHZgyhUVBQcAhAfp40OEwe8pnE2EnkiYoIN98883X3LbFytkhfT169ChxU2+rG9qOR+WmIZAFAl4Q+Pbbbw907dq1hxe6oAMEokCAlvjfuXPnniiUxasy2HFmRL+5JFNWWhEuorpFZMniY6UbLTxWhBAPAiAAAilM4JNPPvmbnQ9UCqOKF91NxyDVWbpdfjg8bhOFPBAAARAIIAFacDAZs+D0iNEbN27cGLGUSCVC4IUXXnhGJJ1IGnRpiVBCmsgQQJdWZKoSBbFBQL06cDKOC1ovrKHTeJfLL7/8GuuUiRSiTKneZKUVsVVUt4gsO/dgVVVVZXZ2do6VXBGZcHisKCI+UgTg8ESqOlEYQQLajxVdp/NDMHtTMq2cpggHJyIfKCuxovZ4qYtstqPPThlkpbXiTPGiukVkyeJjpdv2DW8lEPEgAAIgAALBIbBixYqlWmvog0MfsGXLlj2tjTO6dvODRzpuvfXWaUa63A73Upcd291make3n2n9KjdaePysdej2nABaeDxHDoU+ExD5uFitiSIiw0kxRf/Sr6ioKKfdyWma8oEDBw4quuzY5aUuss9Kn91NXEmeaHntplV4mv2K6jaToY6z4kNp7egUkYcWHnUN4BwEQAAEIkRA9INBzgSlNTpkISF9VrIpDdlH6fbv33+ArpX9s8aMGTPSKr8ST/mUc6NfSmOka9GiRXON8umFm+mjFZjd3rFez4YghxEfs+0+zPi5Vi5SggMEokrg0KFD+117WCAIBAJOICzPsd4MskmTJl1uZT8NxrZKo433UpdWdzLXdKuJ5rebVuQ2FtXtVzqRMqBLS4QS0kSGALq0IlOVKIgFAfrwWCSRFv3SSy/9burUqTdLU5CCgu12U4nWv0hXEOEWledX1YiUA11aftUO9IIACICAJAILFy58WJJoIbHTpk27RSghEoGAhwTg8HgIG6pAAARAwAsC55xzjm97xil/aSu/sstLeuiQrYfkk56NGzdu8EJXWHV4VRdO+LS6SYLebOWkkMgDAgoBdGkpJPAbdQJ+7IGl97GT+U0pLi4uPH78+EmlLr3SJVOPUhbtL7EV1Ws3rVaX3rUd3ZRfNL2eLidheveeVg5aeLREcA0CIAACESDg9R5YRh8co/BkEdMUdbWzQ/K80iVLT7JMgpT/2muvvSJI9pAtcHiCViOwBwRAAARcJEAfZzpcFNlC1L59+/ZYybeKbyFQ4ILkqdfjUWfxSpcbeqiFSm17lM7XrFmzgZzSIJUJDk+QagO2gAAIgIAkAvSBpmPHjh3b3FJB8vr37z9YRB6lvfTSS0eLpDVKQ+vukByjeCXcK12kx85aQIp99Et5tS1U6vgonJNTSuUMbFmo3w0HCESVANbhCeyrB4b5QIC2XLD7rLtlpqjetWvXrkxWp1e6rPQcO3bsSLJlCXP+d955Z70VI4pXb4cikp7SiHBp5XmJZhQRjjQgEDQCGLQctBqBPSAAAiBgTEDUJxFpSUKXljFnxIAACIAACIAACLhAgFa4ppWxXRDlWAQcHsfokBEEQAAEQAAEQMCMgLJFCO0dVlZWVm6WVhsn2rqjzWd03crhufHGGycbJUY4CISdwA/5EfYywH4QAAEQCDoBZXzY6tWr16ttJSdG2fxVHa49d9vZ0crHNQiAAAiAAAiAAAg4JkA7wZOzInJQWq2iXbt2bRfJq02jlaN33WrQsl4ihIEACIAACIAACICAGQFyQsziZcXRej9G6zKpdcLhUdPAOQiAAAiAAAiAgCMCfjk8IjO0qECtxvA4KiUygQAIgAAIgAAIpDQBUcfDTUhBW83ZzbJBFgiAAAiAAAiAQEAJ0Ka12vE1sq7tLuSYEVBmMAsEQAAEQAAEQCBkBI4cOXKsb9++3c8999zvyzY9Ly8vX7YOyAcBEAABEAABEAABQwLKtHQZrTu//vWvZxkqNonAoGUTOIgCARAAARAAARBwTsDtgczJjBOCw+O8HpETBEAABEAABEBAgECyjk8yjo6AeUgCAiAAAiAAAiAAAu4T2L59+1az7i73NUIiCIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACIAACEgm8P8Bk5dVFv9i0ZkAAAAASUVORK5CYII=
" alt="Logo" style="width: 100%; height: 100%; object-fit: cover;">
            </div>
            <h1>MuSe Testing Report</h1>
            <div class="subtitle">Mutation Testing Results for Smart Contracts</div>
        </div>
        
        <div class="summary">
            <div class="info-grid">
                <div class="info-card">
                    <h3>Contract Under Test</h3>
                    <div class="value">{{CONTRACT_NAME}}</div>
                </div>
                <div class="info-card">
                    <h3>Test File</h3>
                    <div class="value">{{TEST_FILE}}</div>
                </div>
                <div class="info-card">
                    <h3>Testing Duration</h3>
                    <div class="value">{{DURATION}} minutes</div>
                </div>
                <div class="info-card">
                    <h3>Mutant Generation Time</h3>
                    <div class="value">{{GENERATION_TIME}} seconds</div>
                </div>
            </div>
            
            <div class="stats-grid">
                <div class="stat-card" onclick="showMutants('generated')">
                    <div class="stat-number">{{TOTAL_MUTANTS}}</div>
                    <div class="stat-label">Generated Mutants</div>
                </div>
                <div class="stat-card live" onclick="showMutants('live')">
                    <div class="stat-number">{{LIVE_MUTANTS}}</div>
                    <div class="stat-label">Live Mutants</div>
                </div>
                <div class="stat-card killed" onclick="showMutants('killed')">
                    <div class="stat-number">{{KILLED_MUTANTS}}</div>
                    <div class="stat-label">Killed Mutants</div>
                </div>
                <div class="stat-card score">
                    <div class="stat-number">{{MUTATION_SCORE}}%</div>
                    <div class="stat-label">Mutation Score</div>
                </div>
            </div>
        </div>
        
        <div class="mutants-section">
            <div id="liveMutantsSection" class="mutants-container">
                <div class="section-title">Live Mutants (Test Suite Needs Improvement)</div>
                <div class="mutants-grid" id="liveMutantsGrid"></div>
            </div>
            
            <div id="killedMutantsSection" class="mutants-container">
                <div class="section-title">Killed Mutants (Well Tested)</div>
                <div class="mutants-grid" id="killedMutantsGrid"></div>
            </div>
            
            <div id="generatedMutantsSection" class="mutants-container">
                <div class="section-title">All Generated Mutants</div>
                <div class="mutants-grid" id="generatedMutantsGrid"></div>
            </div>
        </div>
        
        <div class="footer">
            Generated by MuSe - Mutation Testing Tool for Solidity Smart Contracts
        </div>
    </div>
    
    <script>
        const reportData = {{REPORT_DATA}};
        let currentSection = null;
        
        function showMutants(type) {
            document.querySelectorAll('.mutants-container').forEach(section => {
                section.classList.remove('active');
            });
            
            let sectionId, mutantsList, cssClass;
            
            switch(type) {
                case 'live':
                    sectionId = 'liveMutantsSection';
                    mutantsList = reportData.liveMutantsList;
                    cssClass = 'live';
                    break;
                case 'killed':
                    sectionId = 'killedMutantsSection';
                    mutantsList = reportData.killedMutantsList;
                    cssClass = 'killed';
                    break;
                case 'generated':
                    sectionId = 'generatedMutantsSection';
                    mutantsList = [...reportData.liveMutantsList, ...reportData.killedMutantsList];
                    cssClass = 'generated';
                    break;
            }
            
            const section = document.getElementById(sectionId);
            const grid = section.querySelector('.mutants-grid');
            
            if (grid.children.length === 0) {
                mutantsList.forEach(mutantId => {
                    const mutantDiv = document.createElement('div');
                    mutantDiv.className = \`mutant-item \${reportData.liveMutantsList.includes(mutantId) ? 'live' : 'killed'}\`;
                    const mutationType = reportData.mutantDetails[mutantId] || 'Unknown';
                    mutantDiv.innerHTML = \`
            <div style = "font-weight: bold;" >\${mutantId} </div>
        <div style="font-size: 0.75em; color: #666; margin-top: 4px;">(\${mutationType})</div>\`;
                    grid.appendChild(mutantDiv);
                });
            }
            
            section.classList.add('active');
            currentSection = type;
        }
        
        window.onload = function() {
            showMutants('live');
        }
    </script>
</body>
</html>`;
	}

	// Genera il report HTML
	generateReport() {
		try {
			// Parsa il file di log
			const data = this.parseLogFile();
			if (!data) {
				throw new Error("Impossibile parsare il file di log");
			}

			// Crea la directory di output se non esiste
			if (!fs.existsSync(this.outputDir)) {
				fs.mkdirSync(this.outputDir, { recursive: true });
			}

			// Genera il template HTML
			let htmlTemplate = this.generateHTMLTemplate();

			// Sostituisci i placeholder con i dati reali
			const timestamp = new Date().toLocaleString();
			htmlTemplate = htmlTemplate
				.replace("{{TIMESTAMP}}", timestamp)
				.replace("{{CONTRACT_NAME}}", data.contractName)
				.replace("{{TEST_FILE}}", data.testFile)
				.replace("{{DURATION}}", data.duration)
				.replace("{{GENERATION_TIME}}", data.generationTime)
				.replace("{{TOTAL_MUTANTS}}", data.totalMutants)
				.replace("{{LIVE_MUTANTS}}", data.liveMutantsCount)
				.replace("{{KILLED_MUTANTS}}", data.killedMutantsCount)
				.replace("{{MUTATION_SCORE}}", data.mutationScore)
				.replace("{{REPORT_DATA}}", JSON.stringify(data));

			// Salva il report
			const reportPath = path.join(this.outputDir, "muse-report.html");
			fs.writeFileSync(reportPath, htmlTemplate, "utf8");

			return reportPath;
		} catch (error) {
			console.error("Errore nella generazione del report:", error);
			throw error;
		}
	}
}
